package GamePackage;

public enum SpellTarget {
    ENEMY_MINION,
    ENEMY_HERO,
    ENEMY_FORCE,
    ALLY_MINION,
    ALLY_HERO,
    ALLY_FORCE,
    CELL,
    FORCE,
    ENEMY_FORCES_COL,
    RANDOM_ENEMY_MINION_8,
    FORCE_ROW,
    ENEMY_MINION_RANDOM,
    ALLY_MINION_RANDOM,
    ALLY_FORCE_MELEE,
    ALLY_FORCE_RANDOM,
    ALLY_FORCE_RH_RANDOM
}